name: Cypress Tests
on:
  push:
    branches:
      - main 
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run watch
          wait-on: 'http://localhost:3000' # Waits for above
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
